### ISSUE TITLE
能否加上操作"已打开标签页"的功能~~

### ISSUE THREAD

**Issue by goldenages1989** [octref/lynn#1]
因为我总是在chrome里面打开很多标签,所以我想把相关的标签分成一些组，然后每一个组在一个窗口里面打开，现在我是通过:am把想要分为一组的标签选中加上tag存入书签中（可能我并不想把他们加入书签中)，然后通过查找出这个书签并用C+Enter在新窗口中找开。能否有这样一个功能我打一个命令（比如:t)能列出所有的open tabs，然后我通过C-h选中我要分组的tabs(或者可以键入关键字来搜索所有的open tabs，然后C+S+a全部选中)，然后按C-Enter就可以在新窗口中打开这些标签页，而老窗口中相应的标签页就关闭了,谢谢

**Comment by octref** [comment]
我不确定我理解了你的意思，确认一下哦：
比如某窗口有 10 个 Tab，你是希望能做类似 ”选中所有打开的，带 ＃python 的书签，把它们重新打开在一个新的页面“ 么？

**Comment by octref** [comment]
如果做的话我可能是加一个选项在 search query 里面，限定搜索范围为“当前打开的书签“。然后再加”关闭“，”移动“ 之类的功能。

**Comment by goldenages1989** [comment]
可能是我没表达清楚，我的想法是打一个命令之后,列出这10个tab,然后我选中我想重新打开在新窗口的4个tab，然后按比如说Ctrl+Enter，这4个tab就在一个新的chrome窗口中打开了，而原来的窗口中只剩下了其它的6个tab。（最终的目的就是想把最初在一个chrome窗口中打开的这10个tab，分到2个chrome窗口中)

**Comment by octref** [comment]
如果你说的 10 个 Tab 都是书签的话，我可以加这个功能，而且可以用 #tag 或者 keyword 来 filter。
但是如果只是随便打开的 10 个 Tab 的话，我比较想把这类功能放到自己想做的下一个用来管理 Tab 的 extension 里 （估计6－7月左右能做好吧，最近太忙了）。

**Comment by goldenages1989** [comment]
是随意打开的。好期待你的下一个插件～

**Comment by octref** [comment]
@goldenages1989 
会在 0.3.0 中加入用 `%` 来标记当前已经打开的书签。
比如平时搜索 `blog` 时候会出现 5 个结果，现在打开了其中的两个，那么 `% blog` 和 `blog %` 都只会显示这两个，然后你可以把它们在新的窗口打开。

我并不是很想加入关闭 tab 的功能。感觉不是 Bookmark Manager 份内的功能。
谢谢支持 > <

**Comment by octref** [comment]
在 1e4b3ef 中改为用 `%` 来 toggle 是否只显示当前显示的书签，并不把 `%` 本身加入输入的命令。
